steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/client-chatbot-api/chatbot-api', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/client-chatbot-api/chatbot-api']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'chatbot-api'
    - '--image'
    - 'gcr.io/client-chatbot-api/chatbot-api'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--memory'
    - '2Gi'
    - '--set-env-vars'
    - 'DB_HOST=104.243.44.92,DB_NAME=eddcode1_aidexchatbot,DB_USER=eddcode1_talkbot,DB_PASS=(ruaN^{r)7I&,DB_PORT=3306'
    - '--allow-unauthenticated'

images:
  - 'gcr.io/client-chatbot-api/chatbot-api'